name: Continuous delivery

on:
  push:
    branches: [ main ]

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: tar -czf output.tar.gz build
    - name: Bump version and push tag
      id: bump_tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ steps.bump_tag.outputs.new_tag }}
        prerelease: false
        files: |
          output.tar.gz
    outputs:
      release_tag: ${{ steps.bump_tag.outputs.new_tag }}
  deploy_to_dev:
    uses: ./.github/workflows/deploy_to_env.yml
    needs: cicd
    with:
      release_tag: ${{ needs.cicd.outputs.release_tag }}
      bucket: demo-react-app.trial.studio
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEMO_REACT_APP_AWS_ACCESS_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEMO_REACT_APP_AWS_SECRET }}
      AWS_DEFAULT_REGION: "us-east-2"