name: Deploy to prod

on:
  workflow_dispatch:
    inputs:
      release:
        type: string
        required: true
        description: version of release to deploy

jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/deploy_to_env.yml
        with:
          release: ${{ github.event.inputs.release }}
          bucket: s3://prod-demo-react-app.trial.studio