name: Deploy to dev

on:
  workflow_dispatch:
    inputs:
      release:
        type: string
        required: true
        description: version of release to deploy

jobs:
  deploy_to_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/deploy_to_env.yml@main
        with:
          release: ${{ github.event.inputs.release }}
          bucket: s3://demo-react-app.trial.studio